# Generated by Django 6.0.2 on 2026-03-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
                ('link', models.URLField()),
            ],
        ),
    ]
